// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalKeyPositionDao is internal type for wrapping internal DAO implements.
type internalKeyPositionDao = *internal.KeyPositionDao

// keyPositionDao is the data access object for table key_position.
// You can define custom methods on it to extend its functionality as you wish.
type keyPositionDao struct {
	internalKeyPositionDao
}

var (
	// KeyPosition is globally public accessible object for table key_position operations.
	KeyPosition = keyPositionDao{
		internal.NewKeyPositionDao(),
	}
)

// Fill with you ideas below.
