// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewUserBindTraderTwoDao is internal type for wrapping internal DAO implements.
type internalNewUserBindTraderTwoDao = *internal.NewUserBindTraderTwoDao

// newUserBindTraderTwoDao is the data access object for table new_user_bind_trader_two.
// You can define custom methods on it to extend its functionality as you wish.
type newUserBindTraderTwoDao struct {
	internalNewUserBindTraderTwoDao
}

var (
	// NewUserBindTraderTwo is globally public accessible object for table new_user_bind_trader_two operations.
	NewUserBindTraderTwo = newUserBindTraderTwoDao{
		internal.NewNewUserBindTraderTwoDao(),
	}
)

// Fill with you ideas below.
