// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewUserInfoDao is internal type for wrapping internal DAO implements.
type internalNewUserInfoDao = *internal.NewUserInfoDao

// newUserInfoDao is the data access object for table new_user_info.
// You can define custom methods on it to extend its functionality as you wish.
type newUserInfoDao struct {
	internalNewUserInfoDao
}

var (
	// NewUserInfo is globally public accessible object for table new_user_info operations.
	NewUserInfo = newUserInfoDao{
		internal.NewNewUserInfoDao(),
	}
)

// Fill with you ideas below.
