// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewBinancePositionHistoryDao is internal type for wrapping internal DAO implements.
type internalNewBinancePositionHistoryDao = *internal.NewBinancePositionHistoryDao

// newBinancePositionHistoryDao is the data access object for table new_binance_position_history.
// You can define custom methods on it to extend its functionality as you wish.
type newBinancePositionHistoryDao struct {
	internalNewBinancePositionHistoryDao
}

var (
	// NewBinancePositionHistory is globally public accessible object for table new_binance_position_history operations.
	NewBinancePositionHistory = newBinancePositionHistoryDao{
		internal.NewNewBinancePositionHistoryDao(),
	}
)

// Fill with you ideas below.
