// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewUserOrderTwoDao is internal type for wrapping internal DAO implements.
type internalNewUserOrderTwoDao = *internal.NewUserOrderTwoDao

// newUserOrderTwoDao is the data access object for table new_user_order_two.
// You can define custom methods on it to extend its functionality as you wish.
type newUserOrderTwoDao struct {
	internalNewUserOrderTwoDao
}

var (
	// NewUserOrderTwo is globally public accessible object for table new_user_order_two operations.
	NewUserOrderTwo = newUserOrderTwoDao{
		internal.NewNewUserOrderTwoDao(),
	}
)

// Fill with you ideas below.
