// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewBinanceTradeHistoryDao is internal type for wrapping internal DAO implements.
type internalNewBinanceTradeHistoryDao = *internal.NewBinanceTradeHistoryDao

// newBinanceTradeHistoryDao is the data access object for table new_binance_trade_history.
// You can define custom methods on it to extend its functionality as you wish.
type newBinanceTradeHistoryDao struct {
	internalNewBinanceTradeHistoryDao
}

var (
	// NewBinanceTradeHistory is globally public accessible object for table new_binance_trade_history operations.
	NewBinanceTradeHistory = newBinanceTradeHistoryDao{
		internal.NewNewBinanceTradeHistoryDao(),
	}
)

// Fill with you ideas below.
