// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewBinancePositionDao is internal type for wrapping internal DAO implements.
type internalNewBinancePositionDao = *internal.NewBinancePositionDao

// newBinancePositionDao is the data access object for table new_binance_position.
// You can define custom methods on it to extend its functionality as you wish.
type newBinancePositionDao struct {
	internalNewBinancePositionDao
}

var (
	// NewBinancePosition is globally public accessible object for table new_binance_position operations.
	NewBinancePosition = newBinancePositionDao{
		internal.NewNewBinancePositionDao(),
	}
)

// Fill with you ideas below.
