// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewBinanceTraderDao is internal type for wrapping internal DAO implements.
type internalNewBinanceTraderDao = *internal.NewBinanceTraderDao

// newBinanceTraderDao is the data access object for table new_binance_trader.
// You can define custom methods on it to extend its functionality as you wish.
type newBinanceTraderDao struct {
	internalNewBinanceTraderDao
}

var (
	// NewBinanceTrader is globally public accessible object for table new_binance_trader operations.
	NewBinanceTrader = newBinanceTraderDao{
		internal.NewNewBinanceTraderDao(),
	}
)

// Fill with you ideas below.
