// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalNewTraderInfoDao is internal type for wrapping internal DAO implements.
type internalNewTraderInfoDao = *internal.NewTraderInfoDao

// newTraderInfoDao is the data access object for table new_trader_info.
// You can define custom methods on it to extend its functionality as you wish.
type newTraderInfoDao struct {
	internalNewTraderInfoDao
}

var (
	// NewTraderInfo is globally public accessible object for table new_trader_info operations.
	NewTraderInfo = newTraderInfoDao{
		internal.NewNewTraderInfoDao(),
	}
)

// Fill with you ideas below.
