// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"binance_data_gf/internal/dao/internal"
)

// internalTraderPositionDao is internal type for wrapping internal DAO implements.
type internalTraderPositionDao = *internal.TraderPositionDao

// traderPositionDao is the data access object for table trader_position.
// You can define custom methods on it to extend its functionality as you wish.
type traderPositionDao struct {
	internalTraderPositionDao
}

var (
	// TraderPosition is globally public accessible object for table trader_position operations.
	TraderPosition = traderPositionDao{
		internal.NewTraderPositionDao(),
	}
)

// Fill with you ideas below.
